# Generated by Django 4.2.3 on 2025-12-09 21:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_genre_description_en_genre_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season_number', models.PositiveIntegerField(default=1, verbose_name='season number')),
                ('episode_number', models.PositiveIntegerField(verbose_name='episode number')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_uz', models.TextField(null=True, verbose_name='description')),
                ('description_ru', models.TextField(null=True, verbose_name='description')),
                ('duration', models.IntegerField(help_text='Duration in minutes', verbose_name='duration')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'db_table': 'episodes',
                'ordering': ['season_number', 'episode_number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(choices=[('G', 'G - All Ages'), ('PG', 'PG - Parental Guidance'), ('PG-13', 'PG-13 - Parents Strongly Cautioned'), ('R', 'R - Restricted'), ('NC-17', 'NC-17 - Adults Only')], default='PG-13', max_length=10, verbose_name='age rating'),
        ),
        migrations.AddField(
            model_name='movie',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='available until'),
        ),
        migrations.AddField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show'), ('cartoon', 'Cartoon'), ('documentary', 'Documentary'), ('anime', 'Anime')], default='movie', max_length=20, verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='IMDb rating'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is featured'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_premier',
            field=models.BooleanField(default=False, verbose_name='is premier'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_trending',
            field=models.BooleanField(default=False, verbose_name='is trending'),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='likes count'),
        ),
        migrations.AddField(
            model_name='movie',
            name='premier_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='premier date'),
        ),
        migrations.AddField(
            model_name='movieview',
            name='duration_watched',
            field=models.IntegerField(default=0, help_text='Seconds watched', verbose_name='duration watched'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uz', 'Uzbek'), ('ru', 'Russian'), ('kr', 'Korean'), ('jp', 'Japanese')], default='en', max_length=10, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='video',
            name='subtitle_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('uz', 'Uzbek'), ('ru', 'Russian'), ('kr', 'Korean'), ('jp', 'Japanese')], max_length=10, null=True, verbose_name='subtitle language'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='movies/thumbnails/%Y/%m/%d/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='movie_posters/%Y/%m/%d/', verbose_name='poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='release year'),
        ),
        migrations.AlterField(
            model_name='movieview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='video',
            name='quality',
            field=models.CharField(choices=[('SD', 'SD (480p)'), ('HD', 'HD (720p)'), ('FHD', 'Full HD (1080p)'), ('UHD', 'Ultra HD (4K)')], default='HD', max_length=10, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='movies/videos/%Y/%m/%d/', verbose_name='video file'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('movie', 'quality', 'language')},
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_premier', 'premier_date'], name='movies_is_prem_4bd298_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_featured'], name='movies_is_feat_541cef_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_trending'], name='movies_is_tren_3fedf6_idx'),
        ),
        migrations.AddField(
            model_name='episode',
            name='tv_show',
            field=models.ForeignKey(limit_choices_to={'content_type': 'tv_show'}, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.movie', verbose_name='tv show'),
        ),
        migrations.AddField(
            model_name='genre',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genres', to='movies.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.category', verbose_name='categories'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('tv_show', 'season_number', 'episode_number')},
        ),
    ]
